### ISSUE TITLE
Adjust the README instructions to use builder tool rather than defining main.go from scratch 

### ISSUE THREAD

**Issue by pavankrish123** [rquedas/otel4devs#1]
i think we should be encouraging developers in using the https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder. rather than writing their own main.go components.go the builder generates one for them properly.

The problem with maintaining their own main.go  is that the api's at the moment are unstable and are prone to change and any changes to function signatures will break the collector compilation

Instructions to build collector 

- `go install go.opentelemetry.io/collector/cmd/builder@latest`
- crearte a builder manifest 
```yaml

dist:
  module: go.opentelemetry.io/collector/builder/test/nocore
  include_core: false
  output_path: .
  description: My OpenTelemetry collector
  name: my-collector

receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.40.0
exporters:
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.40.0
extensions:
  - import: go.opentelemetry.io/collector/extension/zpagesextension
    gomod: go.opentelemetry.io/collector v0.40.0
    
```
- builder --config config.yaml
